kind: ConfigMap 
apiVersion: v1 
metadata:
  name: orderer-configmap 
data:
  config.json: |-
    {
      "_comment": "Configuration for CAPER blockchain implementation",
      "application_instance": {
        "MANUFACTURER": {
          "servers": [
            {
              "host": "server-service-manufacturer1",
              "port": 9001
            },
            {
              "host": "server-service-manufacturer2",
              "port": 9002
            },
            {
              "host": "server-service-manufacturer3",
              "port": 9003
            }
          ]
        },
        "SUPPLIER": {
          "servers": [
            {
              "host": "server-service-supplier1",
              "port": 11001
            },
            {
              "host": "server-service-supplier2",
              "port": 11002
            },
            {
              "host": "server-service-supplier3",
              "port": 11003
            }
          ]
        },
        "CARRIER": {
          "servers": [
            {
              "host": "server-service-carrier1",
              "port": 12001
            },
            {
              "host": "server-service-carrier2",
              "port": 12002
            },
            {
              "host": "server-service-carrier3",
              "port": 12003
            }
          ]
        },
        "BUYER": {
          "servers": [
            {
              "host": "server-service-buyer1",
              "port": 13001
            },
            {
              "host": "server-service-buyer2",
              "port": 13002
            },
            {
              "host": "server-service-buyer3",
              "port": 13003
            }
          ]
        }
      },
      "orderers": {
        "servers": [
          {
            "_comment": "by default, the first node in this list is the primary node",
            "host": "orderer-leader-service",
            "port": 14001
          },
          {
            "host": "orderer-leader-proposer",
            "port": 14002
          },
          {
            "host": "orderer-consensus-service1",
            "port": 14003
          },
          {
            "host": "orderer-consensus-service2",
            "port": 14004
          },
          {
            "host": "orderer-consensus-service3",
            "port": 14005
          },
          {
            "host": "orderer-replica-service",
            "port": 14006
          }
        ]
      },
      "nats": {
        "servers": [
          "nats://cloud-nats-svc:4222"
        ]
      },
      "global_consensus_algorithm": "slpbft",
      "consensus": "bpaxos",
      "num_applications": 2
    }
