apiVersion: apps/v1
kind: Deployment
metadata:
 name: orderer-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
    app: orderer
 template:
   metadata:
     labels:
       app: orderer
   spec:

     containers:
     - name: orderer-carrier
       imagePullPolicy: IfNotPresent
       image: orderer-carrier:v1
      #  envFrom:
      #   - configMapRef:
      #       name: orderer-configmap 
       ports:
       - containerPort: 3000
       
