apiVersion: apps/v1
kind: Deployment
metadata:
 name: orderer-deployment-consensus3
spec:
 replicas: 1
 selector:
  matchLabels:
    app: orderer-consensus3
 template:
   metadata:
     labels:
       app: orderer-consensus3
   spec:
     volumes:
     - name: config-vol
       configMap:
        name: orderer-configmap 

     containers:
     - name: orderer
       imagePullPolicy: IfNotPresent
       image: orderer:v1
       volumeMounts:
        - name: config-vol
          mountPath: /etc/config
       args: ["-nodeId=4", "-configFilePath=/etc/config/config.json"]
       ports:
       - containerPort: 3004
    