apiVersion: v1
kind: Service
metadata:
 name: server-service-carrier
 labels:
   app: server-carrier
spec:

 type: NodePort
 ports:
 - port: 12001
   name: http
   nodePort: 30088
 selector:
   app: server-carrier