apiVersion: apps/v1
kind: Deployment
metadata:
 name: server-deployment-buyer1
spec:
 replicas: 1
 selector:
  matchLabels:
    app: server-buyer1
 template:
   metadata:
     labels:
       app: server-buyer1
   spec:
     volumes:
     - name: config-vol
       configMap:
        name: orderer-configmap 

     containers:
     - name: server
       imagePullPolicy: IfNotPresent
       image: server:v1
       volumeMounts:
        - name: config-vol
          mountPath: /etc/config
       args: ["-nodeId=0", "-appName=BUYER", "-configFilePath=/etc/config/config.json"]
       ports:
       - containerPort: 13001
    