apiVersion: apps/v1
kind: Deployment
metadata:
 name: server-deployment-carrier3
spec:
 replicas: 1
 selector:
  matchLabels:
    app: server-carrier3
 template:
   metadata:
     labels:
       app: server-carrier3
   spec:
     volumes:
     - name: config-vol
       configMap:
        name: orderer-configmap 

     containers:
     - name: server
       imagePullPolicy: IfNotPresent
       image: aartij17/server:v1
       volumeMounts:
        - name: config-vol
          mountPath: /etc/config
       args: ["-nodeId=2", "-appName=CARRIER", "-configFilePath=/etc/config/config.json"]
       ports:
       - containerPort: 12003
    